# Generated by Django 5.0.3 on 2024-04-07 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_attachment_link_post_background_music_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 13, 22, 34, 635848, tzinfo=datetime.timezone.utc)),
        ),
    ]
