# Generated by Django 5.0.3 on 2024-04-07 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 14, 56, 44, 581032, tzinfo=datetime.timezone.utc)),
        ),
    ]
