# Generated by Django 5.0.3 on 2024-04-07 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 15, 7, 2, 301736, tzinfo=datetime.timezone.utc)),
        ),
    ]
