# Generated by Django 5.0.3 on 2024-05-11 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 16, 18, 12, 878598, tzinfo=datetime.timezone.utc)),
        ),
    ]
