# Generated by Django 5.0.3 on 2024-04-07 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='old',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_up_at',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
