# Generated by Django 5.0.3 on 2024-04-07 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 13, 39, 5, 954013, tzinfo=datetime.timezone.utc)),
        ),
    ]
