# Generated by Django 5.0.3 on 2024-04-07 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 15, 7, 2, 310220, tzinfo=datetime.timezone.utc)),
        ),
    ]
