# Generated by Django 5.0.3 on 2024-05-10 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 7, 3, 17, 855485, tzinfo=datetime.timezone.utc)),
        ),
    ]
